version: '3.9'

services:
  web:
    build: ./
    container_name: managment_app
    restart: always
    volumes:
      - .:/app
    ports:
      - 8001:8000
    env_file:
      - ./.env
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
